apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs
  namespace:  reactjs-ns
spec:
  replicas: 2
  selector:
    matchLabels:  
      app:  reactjs
  template:
    metadata:
      labels:
        app:  reactjs
    spec:
      containers:
      - name: my-reactjs
        image:  santana20095/react-nodejs:1.0
        ports:
        - containerPort: 3080