apiVersion: v1
kind: Service
metadata:
  name: react-service 
  namespace:  reactjs-ns 
spec:
  selector:
    app:  reactjs 
  ports:  
  - port: 80
    protocol: TCP
    targetPort: 3080
  type: LoadBalancer